$patterns = @(
"VITE_SUPABASE_PROJECT_ID",
"VITE_SUPABASE_URL",
"VITE_SUPABASE_ANON_KEY",
"VITE_APP_NAME",
"VITE_APP_VERSION",
"VITE_API_URL",
"VITE_API_TIMEOUT",
"VITE_AUTH_ENABLED",
"VITE_ENABLE_PDF_EXPORT",
"VITE_ENABLE_NOTIFICATIONS",
"VITE_ENVIRONMENT",
"PORT",
"NODE_ENV",
"DATABASE_URL",
"JWT_SECRET",
"JWT_EXPIRES_IN",
"ALLOWED_ORIGINS",
"SMTP_HOST",
"SMTP_PORT",
"SMTP_USER",
"SMTP_PASS",
"SUPABASE_URL",
"SUPABASE_SERVICE_ROLE_KEY",
"COMPANY_NAME",
"COMPANY_ADDRESS_LINE1",
"COMPANY_ADDRESS_LINE2",
"HOURLY_RATE",
"OVERTIME_RATE",
"INVOICE_SIGNED_URL_TTL_SECONDS",
"SUPABASE_INVOICES_BUCKET",
"INVOICE_DUE_DAYS",
"INVOICE_CURRENCY",
"INVOICE_NUMBER_PREFIX",
"BETTER_AUTH_SECRET",
"BETTER_AUTH_URL",
"GOOGLE_CLIENT_ID",
"GOOGLE_CLIENT_SECRET",
"Client_port",
"Server_port",
"VITE_AUTH_BASE_URL"
)

$files = Get-ChildItem -Path . -Recurse -File | Where-Object { $_.FullName -notmatch "\\node_modules\\" -and $_.FullName -notmatch "\\dist\\" -and $_.FullName -notmatch "\\.git\\" -and $_.Name -ne ".env" -and $_.Name -ne ".env.example" }

$files | Select-String -Pattern $patterns -SimpleMatch | Select-Object Path, Pattern, LineNumber, Line | Format-Table -AutoSize -Wrap
