-- Add invoice columns to submissions table
-- These columns store invoice metadata generated by the backend

ALTER TABLE public.submissions
ADD COLUMN IF NOT EXISTS invoice_number TEXT,
ADD COLUMN IF NOT EXISTS invoice_url TEXT,
ADD COLUMN IF NOT EXISTS invoice_generated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS invoice_due_days INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS invoice_currency TEXT DEFAULT 'USD';

-- Create index on invoice_number for lookups
CREATE INDEX IF NOT EXISTS idx_submissions_invoice_number ON public.submissions(invoice_number);

-- Add comments
COMMENT ON COLUMN public.submissions.invoice_number IS 'Unique invoice number generated by backend';
COMMENT ON COLUMN public.submissions.invoice_url IS 'Path to invoice PDF in Supabase Storage (invoices bucket)';
COMMENT ON COLUMN public.submissions.invoice_generated_at IS 'Timestamp when invoice PDF was generated';
COMMENT ON COLUMN public.submissions.invoice_due_days IS 'Number of days until invoice is due (default 15)';
COMMENT ON COLUMN public.submissions.invoice_currency IS 'Currency for invoice (default USD)';

-- Create invoices storage bucket policy (run separately in Supabase dashboard or via API)
-- Bucket: invoices
-- Access: Private (signed URLs only)
-- File path convention: {contractorId}/{submissionId}/invoice-{invoiceNumber}.pdf
